global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    environment: Monitoring

scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgresql-exporter:9187']
        labels:
          service: 'postgres'
          group: 'postgresql'